export const COMPOSITION = {
  id: "CareerOSDemo",
  width: 1920,
  height: 1080,
  fps: 30,
  durationInFrames: 1080,
};

export const SCENES = [
  {
    key: "problem",
    duration: 150,
    eyebrow: "CAREER DEV TOOLKIT / CAREEROS",
    title: "The record is the easy part.",
    lead: "“90% glue”",
    note: "Workflow shorthand—not a measured metric.",
    detail: "The hard part is moving bounded evidence without inventing claims or loosening privacy.",
  },
  {
    key: "architecture",
    duration: 180,
    eyebrow: "LOCAL-FIRST PIPELINE",
    title: "One deterministic path.",
    lead: "harvest → validate → encrypted SQLCipher store → RAW safe Sheets write → exact read-back → outputs/deploy",
    note: "Tapioca-style Apps Script browser-mode · self-contained · no Tapioca runtime",
    detail: "The encrypted local store stays canonical. Google is a bounded projection boundary.",
  },
  {
    key: "harvest",
    duration: 180,
    eyebrow: "HARVEST + DEDUP",
    title: "Overlap becomes provenance.",
    lead: "thread:delivery-017  +  github:pr-204  →  record:delivery-017",
    note: "Merged source IDs retained · validation always runs · invalid impact stays explicit",
    detail: "Nothing is silently deleted, inferred, or promoted past an error-severity issue.",
  },
  {
    key: "privacy",
    duration: 150,
    eyebrow: "CONSENT BOUNDARY",
    title: "Privacy fails closed.",
    lead: "Destination grant ≠ background grant",
    note: "consent.background.required",
    detail: "A permitted foreground write never authorizes unattended execution.",
  },
  {
    key: "sheets",
    duration: 180,
    eyebrow: "SAFE SHEETS PROJECTION",
    title: "Literal in. Exact out.",
    lead: "03/04/2026  →  '03/04/2026",
    note: "inputMode: RAW · one owned-window update · read-back: UNFORMATTED_VALUE",
    detail: "Only an exact matrix, value, and type match records synced.",
  },
  {
    key: "evals",
    duration: 150,
    eyebrow: "DETERMINISTIC EVAL",
    title: "All 8 stages passed.",
    lead: "Synthetic providers only",
    note: "harvest · validation · encryptedStore · privacy · safeWrite · readBack · outputs · backgroundConsent",
    detail: "Local checks prove the contracts they exercise—not an external account.",
  },
  {
    key: "certification",
    duration: 90,
    eyebrow: "EXTERNAL CERTIFICATION",
    title: "Live Google OAuth certification",
    lead: "NOT RUN",
    note: "No user-authorized Google account was used.",
    detail: "Apps Script deployment, real source reads, RAW write, and exact read-back remain uncertified live.",
  },
];

export const EVAL_STAGES = [
  "harvest",
  "validation",
  "encryptedStore",
  "privacy",
  "safeWrite",
  "readBack",
  "outputs",
  "backgroundConsent",
];
